### ISSUE TITLE
Mechanizm aktualizacji danych w bazie dazych przy nowym miesiącu

### ISSUE THREAD

**Issue by Maciekek** [Maciekek/ProjektZespolowy2015#83]
Napisać skrtypt który w bazie danych przy 1 dniu miesiąca zaktualizuje/przeliczy wydatki użytkowanika
Czy robić to z poziomu serwera czy osobny skrypt zostawiam w kwestii realizującego

**Comment by Jankkol** [comment]
Proste rozwiązania są najlepsze :) nie potrzebujemy skryptu, miesięczne opłaty i dochody zawsze będą na zero, więc jedynie co musieliśmy zrobić to przy każdym pierwszym zerować paymentsy. 

To co zrobiłem ja, to przy requeście sprawdzam czy data miesiąc paymentu zgadza się z aktualnym miesiącem na serwerze. Działa :)
