### ISSUE TITLE
Możliwość dodania nowego cyklicznego wydatku na stronie financeSetting

### ISSUE THREAD

**Issue by Maciekek** [Maciekek/ProjektZespolowy2015#84]
Cykliczny wydatek możemy teraz zmienić i usunąc, trzeba umożliwość jeszcze dodanie na stronie financeSetting

**Comment by Jankkol** [comment]
Pytanie takie od strony używania tego. Czy nie powinniśmy zrobić jednolicie zakładkę "Dodaj miesięczny wydatek" ? Bo jak zrobimy w tym financialSetting to będzie się dziwnie to obsługiwało. Trzeba by zrobić plusik, który dodaje szablon miesięcznego wydatku, ale wtedy kolejne pytanie, kiedy to powinno zostać zapisane do bazy? Kiedy użytkownik wpiszę jakąś wartość? Czy powinien mieć button zapisz obok tego i po zapisaniu powinien się zmienić na usuń/zmień ? 

Myślałem jeszcze nad rozwiązaniem w "Dodaj wydatek", żeby dodać checkboxa "miesięczny wydatek". Tylko musiałbym trochę request przekopać i już tak ładnie by nie wyglądał.

**Comment by Jankkol** [comment]
Ewentualnie na "financeSetting" można zrobić przycisk dodaj i tam obsłużyć to tak jak pop-up z pierwszym zalogowaniem.

**Comment by Maciekek** [comment]
Wydaje mi się, ze lepiej by było to zrobić na tej stronie finance settings, zeby utrzymać to w jednym miejscu, wydaje mi sięze możę byc to przez taki popup jak przy ustawieniach pierwszego logowania

**Comment by Jankkol** [comment]
Jedyna rzecz któa trzeba by zrobić to odświeżanie widoku po oknie dialogu. Nie mam póki co pomysłu, bo nie wywołam requesta z requesta. + znalazłem bug'a, którego trzeba by wrzucić na next iteracje. Mianowicie jak zmieniamy miesięczne obligacje bądź dochody - system łapie freeze, ale dane zmienia. Natomiast jeżeli pomniejszymi trochę okno, tak, żeby nie było widać bocznych paneli - wszystko działa ładnie. To popsuło się po którymś commicie, trzeba to będzie przeanalizować.
